"""Stable identities shared by the native V3 LiDAR matcher components."""

from __future__ import annotations


MATCHER_CONTRACT_ID = "R2B4_SCAN_MATCHER_PROCESS_LATEST_ONLY_V1"
MATCHER_CONFIDENCE_MODEL = "R2B4_SCAN_MATCH_CONFIDENCE_V2"
MATCHER_INTEGRITY_MODEL = "R2B4_SCAN_MATCH_BASIN_INTEGRITY_V1"
MATCHER_TRANSPORT = "process_latest_only"
ODOMETRY_MODE = "LIDAR_FIRST"

POSE_FRAME_ID = "R2B4_BOOT_ROBOT_MAP"
POSE_FRAME_OWNER = "EKF_POSE_ODOMETRY_SSOT"
POSE_FRAME_YAW = "CCW_POSITIVE_LEFT"


__all__ = [
    "MATCHER_CONFIDENCE_MODEL",
    "MATCHER_CONTRACT_ID",
    "MATCHER_INTEGRITY_MODEL",
    "MATCHER_TRANSPORT",
    "ODOMETRY_MODE",
    "POSE_FRAME_ID",
    "POSE_FRAME_OWNER",
    "POSE_FRAME_YAW",
]
